export const UESER_UPDATE = 'UESER_UPDATE'
export const UESER_SWITCH_UPDATE = 'UESER_SWITCH_UPDATE'
export const PROJECT_SWITCH_UPDATE = 'PROJECT_SWITCH_UPDATE'
export const SHOW_GALAXY_UPDATE = 'SHOW_GALAXY_UPDATE'
